name: ImageJ
title: ImageJ
description: ImageJ is an open source image processing program designed for scientific multidimensional images.
image: /assets/images/logo.png
markdown: kramdown
kramdown:
  syntax_highlighter: rogue
plugins:
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "" # NB: all files in the project
      type: pages
    values:
      layout: page
  -
    scope:
      path: "_pages/users"
      type: pages
    values:
      icon: https://upload.wikimedia.org/wikipedia/commons/9/90/Ic_person_48px.svg
  -
    scope:
      path: "_pages/plugins"
      type: pages
    values:
      icon: /media/icons/plugin.png
  -
    scope:
      path: "_pages/formats"
      type: pages
    values:
      icon: /media/icons/plugin.png
  -
    scope:
      path: "_pages/plugins/trackmate"
      type: pages
    values:
      icon: /media/icons/trackmate.png

