name: ImageJ
title: ImageJ
markdown: kramdown
kramdown:
  syntax_highlighter: rogue
plugins:
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "" # NB: all files in the project
      type: pages
    values:
      layout: page
