name: ImageJ
title: ImageJ
description: ImageJ is an open source image processing program designed for scientific multidimensional images.
image: /assets/images/logo.png
markdown: kramdown
kramdown:
  syntax_highlighter: rogue
plugins:
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "" # NB: all files in the project
      type: pages
    values:
      layout: page
  -
    scope:
      path: "_pages"
      type: pages
    values:
      icon: /media/icons/40px-information-sign.png
  -
    scope:
      path: "_pages/plugins"
      type: pages
    values:
      icon: /media/icons/plugin.png
  -
    scope:
      path: "_pages/formats"
      type: pages
    values:
      icon: /media/icons/default.png
  -
    scope:
      path: "_pages/plugins/trackmate"
      type: pages
    values:
      icon: /media/icons/trackmate-icon120x120-color.png

